[package]
name = "sovereign_compressor"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # Compiles down to sovereign_compressor.dll

[dependencies]
zstd = "0.13"
rayon = "1.8" # Multi-threaded parallel iterator
